oldsport1120/freemarket_sample_70h

Gemfile
Gemfile.lock
config/environments/production.rb
config/unicorn.rb

Unicornのインストール
config/unicorn.rbを作成
EC2のサーバでUnicornを起動できるようにする

Unicornの設定

---

app/assets/stylesheets/modules/_home.scss
app/views/home/top.html.haml

- 写真画像の位置修正
- 画像３つ使用div　類似２箇所のマークアップ
- 画像のpositionを変更して見本と似せる必要があった
- 写真嵌め込み３箇所は類似していたので、同じHamlで記述

Info_wrapper_basic

---

app/assets/javascripts/products.coffee
app/assets/stylesheets/products.scss
app/controllers/products_controller.rb
app/helpers/products_helper.rb
test/controllers/products_controller_test.rb

#what
・rails g コマンドで productsコントローラーを生成
#why
・コントローラーのみ生成のため、アクション等は各自で設定していきましょう！

商品関連ページコントローラー設定

---

app/assets/stylesheets/modules/_home.scss

- 画像表示不具合の解消のための実験
- Asset Pipeline のために、digestがかかり表示がうまくいっていないかを確かめる作業。

background-image-settings-updated

---

app/controllers/application_controller.rb
app/views/devise/registrations/new.html.haml
app/views/home/top.html.haml
config/routes.rb
db/migrate/20200513125135_devise_create_users.rb
db/schema.rb
db/seeds.rb

新規登録機能・ログイン機能の実装
- マイグレーションファイル
- application_controller.rb
- views/devise/registrations/new.html.haml
の記述精査
- ログイン・ログアウト機能の実装

Sign_up_features

---

.rspec
spec/models/user_spec.rb

ユーザー登録機能・ログイン・ログアウト機能とそれに付随するテストなど
ユーザー登録機能は以下のビジネスルールで入力フォーム作成
app/views/devise/registrations/new.html.haml
- ユーザー情報
- ニックネームが必須
- メールアドレスは一意である
- メールアドレスは@とドメインを含む必要がある
- パスワードが必須
- パスワードは7文字以上
- パスワードは確認用を含めて2回入力する
- 本人確認情報
- ユーザー本名が、名字と名前でそれぞれ必須
- ユーザー本名は全角で入力させる
- ユーザー本名のふりがなが、名字と名前でそれぞれ必須
- ユーザー本名のふりがなは全角で入力させる
- 生年月日が必須
- 商品送付先住所情報
- 送付先氏名が、名字と名前でそれぞれ必須
- 送付先氏名のふりがなが、名字と名前でそれぞれ必須
- 郵便番号が必須
- 都道府県が必須
- 市区町村が必須
- 番地が必須
- マンション名やビル名、そしてその部屋番号は任意
- お届け先の電話番号は任意
- devise
- user.rb
- devise.rb 
- マイグレーションファイル　に記述
- spec/models/user_spec.rb に記述
- 今回のプルリクエストに編集ファイルとして存在していないものは、最新にマスターに準じています。

login_sign_up_test_features

---

app/views/home/top.html.haml
config/routes.rb

トップページからマイページのルーティング実験
ログイン状態の時だけ、トップからマイページに遷移できるようにしたい。

Routing_top_to_mypage

---

app/views/users/index.html.haml
config/routes.rb

試験的にヘッダーとフッターを配置
ヘッダーとフッターの共通化の検討と、sassの変更の確認。

header_footer_added

---

app/models/product.rb
config/routes.rb
db/migrate/20200518171824_create_products.rb
db/schema.rb
spec/models/product_spec.rb

商品出品機能実装の為の、モデル・ルーティングを設定する。
複数名で作業を行える状態までの環境を整備する。

[WIP]商品出品機能のモデル、ルーティングの設定

---

db/migrate/20200513125135_devise_create_users.rb
db/schema.rb

新規登録画面での生年月日入力の不具合解消のための実験
一度できていた新規登録に不具合が生じているので解消実験
データ型をdate から
t.string  :date_of_birth,                 null: false
に変更して実験予定。

migration_files_reset

---

config/application.rb

Timezone_reset

---

db/migrate/20200513125135_devise_create_users.rb
db/schema.rb

date_selectのデータ型を変更。
string から　dateに

date_select_altered

---

app/models/picture.rb
app/models/product.rb
app/views/products/new.html.haml

商品出品機能においての写真投稿フォームの実装
商品出品時、写真の投稿は必須のため

商品出品機能　写真投稿実装

---

app/assets/javascripts/cards.coffee
app/assets/stylesheets/cards.scss
app/controllers/cards_controller.rb
app/helpers/cards_helper.rb
app/models/card.rb
db/migrate/20200523060627_create_cards.rb
spec/helpers/cards_helper_spec.rb
spec/models/card_spec.rb
spec/requests/cards_request_spec.rb

#what
クレジットカード登録に関するコントローラーとモデルの作成
#why
コントローラーとモデルのみの作成

カード登録に関するコントローラーとモデルの作成

---

app/controllers/products_controller.rb
config/routes.rb

#what
buyのルーティング設定
#why
７つのアクション以外のアクションを設定する場合の(:idがつく)memberを用いて設定

buyのルーティングの追加

---

app/assets/stylesheets/modules/_side_bar.scss

マイページのフッター部分が、中央のビューに重なっているものを調整する。
ビューの見た目が悪いのを修正する。

[WIP]マイページのフッター部分の調整

---

app/assets/stylesheets/modules/_products.scss
app/models/product.rb
app/views/products/new.html.haml

商品出品フォームでの複数枚画像の登録機能を実装する。
- 商品の状態がわかるよう複数枚の写真登録が必要

[WIP]写真の複数枚登録機能の実装

---

app/models/user.rb
app/views/devise/registrations/new.html.haml
db/migrate/20200513125135_devise_create_users.rb

新規ログインの生年月日の初期表示の変更
メールの登録時のバリデーション追加
ふりがな入力欄のvalidation（かなのみ入力可に）
全角入力のvalidation
より登録内容をふるいにかけるための記述。

validation_updated

---

app/assets/stylesheets/modules/_products.scss
app/views/home/top.html.haml
app/views/products/new.html.haml
app/views/products/show.html.haml
app/views/users/_side_bar.html.haml
db/schema.rb

各リンクの設定
リンクをつなげながらページ間の繋がりを把握
---
- _side_bar.html.haml （マイページ）
ログアウトをリンク設定
支払い方法をリンク設定
出品するをリンク設定
- products/new.html.haml
ヘッダーのロゴからトップにリンク設定
- products/show.html.haml
出品ボタンからリンク設定（ログインしていないときはログインへ遷移）
ログイン時とログアウト時で表示を切替
- トップページ
出品ボタンからリンク設定（ログインしていないときはログインへ遷移）

Links_updated

---

Gemfile
Gemfile.lock
app/controllers/products_controller.rb
app/models/product.rb
app/models/user.rb
db/migrate/20200518171824_create_products.rb
db/schema.rb

出品機能が正しく実装できていない
コードの調整を行う
本番、ローカルで正しく出品ができるようにする

[WIP]商品出品機能の修正

---

app/assets/javascripts/comments.coffee
app/assets/stylesheets/comments.scss
app/assets/stylesheets/modules/_products.scss
app/controllers/comments_controller.rb
app/controllers/products_controller.rb
app/helpers/comments_helper.rb
app/models/comment.rb
app/models/product.rb
app/models/user.rb
app/views/products/show.html.haml
config/routes.rb
db/migrate/20200612175622_create_comments.rb
db/schema.rb
spec/helpers/comments_helper_spec.rb
spec/models/comment_spec.rb
spec/requests/comments_request_spec.rb

商品についてのコメント・質問機能の実装
フリマアプリの各商品に対し、ログインしたユーザーならコメントや質問ができるようにする。

Comment_feature

---

app/uploaders/image_uploader.rb

image_uploaderの記述を変更
商品の写真が表示されるように修正する

[WIP]商品一覧写真表示の修正

---

app/controllers/products_controller.rb
app/views/products/get_category_children.json.jbuilder
app/views/products/get_category_grandchildren.json.jbuilder
app/views/products/index.html.haml
app/views/products/new.html.haml
app/views/products/show.html.haml
db/schema.rb

#what
フリマアプリのカテゴリー機能（サーバーサイド）の実装のコード
#why
コードレビューお願いして確認してもらうため

[WIP]カテゴリ機能の実装

---

app/assets/stylesheets/modules/_products_new.scss
app/controllers/products_controller.rb
app/models/user.rb
app/views/products/new.html.haml

[what]
商品出品機能の訂正。
[why]
前回マージした際にエラーが発生したため

correction

---

app/controllers/cards_controller.rb

本番環境エラー解決の為のプルリク

---

app/controllers/cards_controller.rb
db/migrate/20200523060627_create_cards.rb
db/schema.rb

マイグレーションファイルの修正

---

README.md
db/migrate/20200518171824_create_products.rb
db/schema.rb

マイグレーションファイルでカラムの型を修正
数字で登録されており、選択され、登録されたものが保存できていない

[WIP]shipping_periodカラムの修正

---

db/seeds.rb

- seeds.rbの訂正
- 初期に作成したseeds.rbデータがバリデーションの更新で古い記載になったので、コメントアウト。

rails-seeds-adjustment

---

app/controllers/products_controller.rb
app/views/products/buy.html.haml

購入ページのビューを修正
詳細ページから購入ページに遷移した際に、購入ページに記載されている情報が異なる

[WIP]購入ページの修正

---

app/assets/stylesheets/purchase.scss
app/controllers/products_controller.rb
app/views/purchase/done.html.haml
app/views/purchase/index.html.haml

購入時、購入ユーザーのidをbuyer_idへ登録するように記述
購入済みの商品がわかるようにするため

[WIP]購入済商品へのタグ表示

---

app/controllers/categorys_controller.rb
app/controllers/products_controller.rb
app/views/categorys/show.html.haml

[what]
カテゴリー一覧ページの訂正
[why]
カテゴリー項目を選択するとエラーが出るため

correctuon
